### ISSUE TITLE
Data download

### ISSUE THREAD

**Issue by komalsrathi** [d3b-center/celllines-profiling-analysis#1]
- [ ] Download data from https://github.com/AlexsLemonade/OpenPBTA-analysis. 
- [ ] Refer to sample sheet of cell lines/tumor samples.

**Comment by jharenza** [comment]
Issue moved to [d3b-center/bixeng #375](https://github.com/d3b-center/bixeng/issues/375) via [**ZenHub**](https://www.zenhub.com/)
