### ISSUE TITLE
Stemness profiling

### ISSUE THREAD

**Issue by komalsrathi** [d3b-center/celllines-profiling-analysis#2]
Try these on expression data:

- [ ] [Stem Checker](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4489266/) 
- [ ] [OCLR](https://www.cell.com/cell/pdf/S0092-8674(18)30358-1.pdf)

**Comment by jharenza** [comment]
Issue moved to [d3b-center/bixu-tracker #376](https://github.com/d3b-center/bixu-tracker/issues/376) via [**ZenHub**](https://www.zenhub.com/)
